---
version: 2
models:
- name: "model_parent_all_only_seed_pipeline_1_Join_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_parent_all_only_seed_pipeline_1_source"
  database: "hive_metastore"
  schema: "qa_db_warehouse"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_parent_all_only_seed_pipeline_1_post_Join_1_0"
    tags:
    - "prophecy_temp"
